name: app1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  weather: ^3.1.1
  intl: ^0.18.1

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/rain.png
    - assets/rain_w.png
    - assets/him.png
    - assets/rain_s.png
    - assets/wind.png
    - assets/cloud_w.png
    - assets/cloud.png
    - assets/clear.png
    - assets/clear_w.png
    - assets/drizzle_w.png
    - assets/drizzle.png
    - assets/snow_w.png
    - assets/snow.png
    - assets/storm_w.png
    - assets/storm.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
#     - family: Inria Sans
#       fonts:
#         - asset: fonts/InriaSans-Regular.ttf
#         - asset: fonts/InriaSans-Bold.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
